apiVersion: apps/v1
kind: Deployment

metadata:
  name: chatbot-deployment

spec:
  replicas: 3  # Number of instances

  selector:
    matchLabels:
      app: chatbot

  template:
    metadata:
      labels:
        app: chatbot

    spec:
      containers:
        - name: chatbot
          image: chatbot-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
